// Generated by https://quicktype.io

export interface IProducts {
  id: number;
  code: string;
  name: string;
  price: string;
  description: string;
  photo: IPhoto;
  details: IDetail[];
}

export interface IDetail {
  label: string;
  value: string;
}

export interface IPhoto {
  filename: string;
  link: string;
  credit: string;
}
